SDK = ../..
include $(SDK)/sdk.mk

# Module metadata
MODULE_NAME    = hello_world
MODULE_VERSION = 1.2.3
MODULE_AUTHOR  = Sample Author
MODULE_DESC    = A simple hello world kernel module.

all: $(TARGET)